'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, FileText, Share2, Calendar } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAtmosphereStore } from '@/stores/atmosphereStore';
import { useUserStore } from '@/stores/userStore';

export default function HealthDataExport() {
    const [isExporting, setIsExporting] = useState(false);
    const { aqi, pm25, temperature, humidity } = useAtmosphereStore();
    const user = useUserStore(state => state.user);

    const generatePDF = async () => {
        setIsExporting(true);
        toast.loading('Generating health report...');

        try {
            // Dynamically import jsPDF to reduce initial bundle size
            const { default: jsPDF } = await import('jspdf');
            await import('jspdf-autotable');

            const doc = new jsPDF();
            const pageWidth = doc.internal.pageSize.getWidth();

            // Header
            doc.setFillColor(59, 130, 246);
            doc.rect(0, 0, pageWidth, 40, 'F');

            doc.setTextColor(255, 255, 255);
            doc.setFontSize(24);
            doc.setFont('helvetica', 'bold');
            doc.text('AEROVITAL NAVIGATOR', pageWidth / 2, 20, { align: 'center' });

            doc.setFontSize(12);
            doc.setFont('helvetica', 'normal');
            doc.text('Atmospheric Health Report', pageWidth / 2, 30, { align: 'center' });

            // Patient Info
            doc.setTextColor(0, 0, 0);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Patient Information', 20, 55);

            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.text(`Name: ${user?.name || 'Not specified'}`, 20, 65);
            doc.text(`Age: ${user?.age || 'Not specified'}`, 20, 72);
            doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, 79);
            doc.text(`Report Time: ${new Date().toLocaleTimeString()}`, 20, 86);

            // Current Atmospheric Conditions
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Current Atmospheric Conditions', 20, 100);

            const conditionsData = [
                ['Metric', 'Value', 'Status'],
                ['Air Quality Index (AQI)', aqi.toString(), getAQIStatus(aqi)],
                ['PM2.5 Concentration', `${pm25} µg/m³`, getPM25Status(pm25)],
                ['Temperature', `${temperature}°C`, 'Normal'],
                ['Humidity', `${humidity}%`, 'Normal']
            ];

            (doc as any).autoTable({
                startY: 105,
                head: [conditionsData[0]],
                body: conditionsData.slice(1),
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246] },
                margin: { left: 20, right: 20 }
            });

            // Health Risk Assessment
            const finalY = (doc as any).lastAutoTable.finalY + 10;
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Health Risk Assessment', 20, finalY);

            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            const riskText = getRiskAssessment(aqi, user);
            const splitText = doc.splitTextToSize(riskText, pageWidth - 40);
            doc.text(splitText, 20, finalY + 7);

            // Recommendations
            const recY = finalY + 7 + (splitText.length * 5) + 10;
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Recommendations', 20, recY);

            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            const recommendations = getRecommendations(aqi);
            let currentY = recY + 7;
            recommendations.forEach((rec, index) => {
                doc.text(`${index + 1}. ${rec}`, 25, currentY);
                currentY += 7;
            });

            // Footer
            doc.setFontSize(8);
            doc.setTextColor(128, 128, 128);
            doc.text('Generated by AeroVital Navigator - Atmospheric Health Protection System', pageWidth / 2, 280, { align: 'center' });
            doc.text('For medical advice, please consult a healthcare professional', pageWidth / 2, 285, { align: 'center' });

            // Save PDF
            doc.save(`AeroVital_Health_Report_${new Date().toISOString().split('T')[0]}.pdf`);

            toast.dismiss();
            toast.success('Health report downloaded successfully!');
        } catch (error) {
            console.error('PDF generation error:', error);
            toast.dismiss();
            toast.error('Failed to generate PDF report');
        } finally {
            setIsExporting(false);
        }
    };

    const exportCSV = () => {
        const csvData = [
            ['AeroVital Health Data Export'],
            ['Generated:', new Date().toLocaleString()],
            [''],
            ['Metric', 'Value', 'Unit'],
            ['Air Quality Index', aqi, 'AQI'],
            ['PM2.5', pm25, 'µg/m³'],
            ['Temperature', temperature, '°C'],
            ['Humidity', humidity, '%'],
            [''],
            ['User Information'],
            ['Name', user?.name || 'Not specified'],
            ['Age', user?.age || 'Not specified']
        ];

        const csv = csvData.map(row => row.join(',')).join('\n');
        const blob = new Blob([csv], { type: 'text/csv' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `AeroVital_Data_${new Date().toISOString().split('T')[0]}.csv`;
        a.click();
        window.URL.revokeObjectURL(url);

        toast.success('CSV data exported successfully!');
    };

    const shareData = async () => {
        const shareText = `🌬️ AeroVital Health Status

📊 Current Conditions:
• AQI: ${aqi}
• PM2.5: ${pm25} µg/m³
• Temperature: ${temperature}°C
• Humidity: ${humidity}%

Status: ${getAQIStatus(aqi)}

Generated: ${new Date().toLocaleString()}`;

        if (navigator.share) {
            try {
                await navigator.share({
                    title: 'AeroVital Health Status',
                    text: shareText
                });
                toast.success('Shared successfully!');
            } catch (error) {
                if ((error as Error).name !== 'AbortError') {
                    console.error('Share error:', error);
                }
            }
        } else {
            await navigator.clipboard.writeText(shareText);
            toast.success('Copied to clipboard!');
        }
    };

    return (
        <div className="space-y-3">
            <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                <FileText size={20} />
                Export Health Data
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={generatePDF}
                    disabled={isExporting}
                    className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-bold py-3 px-4 rounded-xl hover:from-blue-700 hover:to-indigo-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                >
                    <Download size={18} />
                    PDF Report
                </motion.button>

                <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={exportCSV}
                    className="bg-gradient-to-r from-green-600 to-emerald-600 text-white font-bold py-3 px-4 rounded-xl hover:from-green-700 hover:to-emerald-700 transition-all flex items-center justify-center gap-2"
                >
                    <Calendar size={18} />
                    CSV Data
                </motion.button>

                <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={shareData}
                    className="bg-gradient-to-r from-purple-600 to-pink-600 text-white font-bold py-3 px-4 rounded-xl hover:from-purple-700 hover:to-pink-700 transition-all flex items-center justify-center gap-2"
                >
                    <Share2 size={18} />
                    Share
                </motion.button>
            </div>
        </div>
    );
}

// Helper functions
function getAQIStatus(aqi: number): string {
    if (aqi <= 50) return 'Good';
    if (aqi <= 100) return 'Moderate';
    if (aqi <= 150) return 'Unhealthy for Sensitive Groups';
    if (aqi <= 200) return 'Unhealthy';
    if (aqi <= 300) return 'Very Unhealthy';
    return 'Hazardous';
}

function getPM25Status(pm25: number): string {
    if (pm25 <= 12) return 'Good';
    if (pm25 <= 35.4) return 'Moderate';
    if (pm25 <= 55.4) return 'Unhealthy for Sensitive';
    if (pm25 <= 150.4) return 'Unhealthy';
    if (pm25 <= 250.4) return 'Very Unhealthy';
    return 'Hazardous';
}

function getRiskAssessment(aqi: number, user: any): string {
    const baseRisk = aqi > 150 ? 'HIGH RISK' : aqi > 100 ? 'MODERATE RISK' : 'LOW RISK';
    const conditions = user?.healthConditions || [];

    let assessment = `Current Risk Level: ${baseRisk}. `;

    if (aqi > 150) {
        assessment += 'Air quality is unhealthy. Limit outdoor activities and use air purifiers indoors. ';
    } else if (aqi > 100) {
        assessment += 'Sensitive individuals should reduce prolonged outdoor exertion. ';
    } else {
        assessment += 'Air quality is acceptable for most individuals. ';
    }

    if (conditions.includes('respiratory')) {
        assessment += 'Due to respiratory conditions, extra precautions are recommended. ';
    }

    return assessment;
}

function getRecommendations(aqi: number): string[] {
    const recs = [];

    if (aqi > 150) {
        recs.push('Avoid outdoor activities, especially strenuous exercise');
        recs.push('Keep windows and doors closed');
        recs.push('Use air purifiers with HEPA filters');
        recs.push('Wear N95 masks if you must go outside');
        recs.push('Monitor symptoms and seek medical attention if needed');
    } else if (aqi > 100) {
        recs.push('Limit prolonged outdoor exertion');
        recs.push('Consider indoor exercise alternatives');
        recs.push('Keep rescue medications accessible');
    } else {
        recs.push('Maintain regular outdoor activities');
        recs.push('Stay hydrated and maintain healthy lifestyle');
        recs.push('Monitor air quality for changes');
    }

    return recs;
}
